package com.kenlu.crypto.analysis.domain;

// NO data for ACT, LET, ECC, RVN
public enum Crypto {
    BTC, ETH, XRP, BCH, LTC, ADA, XLM, IOT, NEO, XMR,
    DASH, XEM, ETC, QTUM, LSK, BTG, BTCP, ZEC, XVG, XRB,
    BCN, STEEM, BTS, BCD, WAN, SC, DOGE, STRAT, WAVES, DCR,
    KMD, ARDR, DGB, ARK, HSR, PIVX, CNX, SYS, FCT, MONA,
    RDD, ELA, GXS, XZC, NXT, GBYTE, SMART, NEBL, ETN, SKY, /*ACT*/
    PART, EMC, NXS, TPAY, ZEN, BTX, BOS, POA, VTC, GAME,
    UBQ, GRE, GRS, BLOCK, BTCD, LCC, XDN, NAV, BAY, CLOAK,
    EMC2, MNX, ION, PPC, SLS, PURA, VIA, XCP, XAS, ZCL,
    FTC, LBC, BURST, NLG, BCO, ETP, DCT, ECA, XP, SBD,
    CSC, XBY, /*LET,*/ XSH, AEON, /*RVN*/ ONION, SHIFT, /*ECC*/ XEL, POT, CRW, HTML
}
